# Generated by Erlang.mk. Edit at your own risk!

src/p06.erl:: src/p05.erl; @touch $@
src/p07.erl:: src/p05.erl; @touch $@
src/p08.erl:: src/p05.erl; @touch $@
src/p15.erl:: src/p05.erl; @touch $@

COMPILE_FIRST += p05
